services:
  app:
    extends:
      file: ./docker-compose.yml
      service: app
    environment:
      - DB_TYPE=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}

    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - app_network

  migrate:
    extends:
      file: build/postgres/docker-compose.yml
      service: migrate
    networks:
      - app_network

  postgres:
    extends:
      file: build/postgres/docker-compose.yml
      service: postgres
    networks:
      - app_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    extends:
      file: build/redis/docker-compose.yml
      service: redis
    networks:
     - app_network


volumes:
  postgres-data:
  redis-data:


networks:
  app_network:
    driver: bridge
