services:
  app:
    extends:
      file: ./docker-compose.yml
      service: app
    environment:
      - DB_TYPE=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - app_network

  migrate:
    extends:
      file: build/postgres/docker-compose.yml
      service: migrate
    networks:
      - app_network

  postgres:
    extends:
      file: build/postgres/docker-compose.yml
      service: postgres
    networks:
      - app_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


networks:
  app_network:
    driver: bridge
