services:
  app:
    extends:
      file: ./docker-compose.yml
      service: app
    environment:
      - DB_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network

  redis:
    extends:
      file: build/redis/docker-compose.yml
      service: redis
    networks:
     - app_network
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  app_network:
    driver: bridge