// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Comment struct {
	ID        string     `json:"id"`
	User      *User      `json:"user"`
	Replies   []*Comment `json:"replies"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"createdAt"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	User          *User      `json:"user"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	IsCommentable bool       `json:"isCommentable"`
	Comments      []*Comment `json:"comments"`
	CreatedAt     time.Time  `json:"createdAt"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type SortBy string

const (
	SortByNewest SortBy = "NEWEST"
	SortByOldest SortBy = "OLDEST"
	SortByTop    SortBy = "TOP"
)

var AllSortBy = []SortBy{
	SortByNewest,
	SortByOldest,
	SortByTop,
}

func (e SortBy) IsValid() bool {
	switch e {
	case SortByNewest, SortByOldest, SortByTop:
		return true
	}
	return false
}

func (e SortBy) String() string {
	return string(e)
}

func (e *SortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortBy", str)
	}
	return nil
}

func (e SortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
